// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	dto "git.garena.com/sea-labs-id/batch-01/aaron-lee/final-project-backend/dto"
	mock "github.com/stretchr/testify/mock"

	models "git.garena.com/sea-labs-id/batch-01/aaron-lee/final-project-backend/models"

	repositories "git.garena.com/sea-labs-id/batch-01/aaron-lee/final-project-backend/repositories"
)

// AdminService is an autogenerated mock type for the AdminService type
type AdminService struct {
	mock.Mock
}

// AdminUserDetails provides a mock function with given fields: id
func (_m *AdminService) AdminUserDetails(id int) (*dto.UserDetailsRes, error) {
	ret := _m.Called(id)

	var r0 *dto.UserDetailsRes
	if rf, ok := ret.Get(0).(func(int) *dto.UserDetailsRes); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserDetailsRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AdminUserReferralDetails provides a mock function with given fields: id
func (_m *AdminService) AdminUserReferralDetails(id int) (*dto.UserReferralDetailsRes, error) {
	ret := _m.Called(id)

	var r0 *dto.UserReferralDetailsRes
	if rf, ok := ret.Get(0).(func(int) *dto.UserReferralDetailsRes); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserReferralDetailsRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AdminUserTransaction provides a mock function with given fields: q, id
func (_m *AdminService) AdminUserTransaction(q *repositories.Query, id int) (*[]dto.TransRes, error) {
	ret := _m.Called(q, id)

	var r0 *[]dto.TransRes
	if rf, ok := ret.Get(0).(func(*repositories.Query, int) *[]dto.TransRes); ok {
		r0 = rf(q, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]dto.TransRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*repositories.Query, int) error); ok {
		r1 = rf(q, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AdminUsersList provides a mock function with given fields:
func (_m *AdminService) AdminUsersList() (*[]dto.UsersListRes, error) {
	ret := _m.Called()

	var r0 *[]dto.UsersListRes
	if rf, ok := ret.Get(0).(func() *[]dto.UsersListRes); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]dto.UsersListRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChangeUserStatus provides a mock function with given fields: id
func (_m *AdminService) ChangeUserStatus(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreatePromotion provides a mock function with given fields: data
func (_m *AdminService) CreatePromotion(data *dto.PromotionReq) (*dto.PromotionReq, error) {
	ret := _m.Called(data)

	var r0 *dto.PromotionReq
	if rf, ok := ret.Get(0).(func(*dto.PromotionReq) *dto.PromotionReq); ok {
		r0 = rf(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PromotionReq)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*dto.PromotionReq) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeletePromotion provides a mock function with given fields: id
func (_m *AdminService) DeletePromotion(id int) (*models.Promotion, error) {
	ret := _m.Called(id)

	var r0 *models.Promotion
	if rf, ok := ret.Get(0).(func(int) *models.Promotion); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Promotion)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EligibleMerchandiseList provides a mock function with given fields:
func (_m *AdminService) EligibleMerchandiseList() (*[]models.Merchandise, error) {
	ret := _m.Called()

	var r0 *[]models.Merchandise
	if rf, ok := ret.Get(0).(func() *[]models.Merchandise); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]models.Merchandise)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMerchStock provides a mock function with given fields:
func (_m *AdminService) GetMerchStock() (*[]models.Merchstock, error) {
	ret := _m.Called()

	var r0 *[]models.Merchstock
	if rf, ok := ret.Get(0).(func() *[]models.Merchstock); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]models.Merchstock)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPromotion provides a mock function with given fields:
func (_m *AdminService) GetPromotion() (*[]models.Promotion, error) {
	ret := _m.Called()

	var r0 *[]models.Promotion
	if rf, ok := ret.Get(0).(func() *[]models.Promotion); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]models.Promotion)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Merchandise provides a mock function with given fields: id
func (_m *AdminService) Merchandise(id int) (*models.Merchandise, error) {
	ret := _m.Called(id)

	var r0 *models.Merchandise
	if rf, ok := ret.Get(0).(func(int) *models.Merchandise); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Merchandise)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MerchandiseStatus provides a mock function with given fields: data
func (_m *AdminService) MerchandiseStatus(data *dto.MerchandiseStatus) error {
	ret := _m.Called(data)

	var r0 error
	if rf, ok := ret.Get(0).(func(*dto.MerchandiseStatus) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateMerchStocks provides a mock function with given fields: data
func (_m *AdminService) UpdateMerchStocks(data *dto.UpdateMerchStocksReq) (*models.Merchstock, error) {
	ret := _m.Called(data)

	var r0 *models.Merchstock
	if rf, ok := ret.Get(0).(func(*dto.UpdateMerchStocksReq) *models.Merchstock); ok {
		r0 = rf(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Merchstock)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*dto.UpdateMerchStocksReq) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePromotion provides a mock function with given fields: id, data
func (_m *AdminService) UpdatePromotion(id int, data *dto.PatchPromotionReq) (*dto.PatchPromotionReq, error) {
	ret := _m.Called(id, data)

	var r0 *dto.PatchPromotionReq
	if rf, ok := ret.Get(0).(func(int, *dto.PatchPromotionReq) *dto.PatchPromotionReq); ok {
		r0 = rf(id, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PatchPromotionReq)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, *dto.PatchPromotionReq) error); ok {
		r1 = rf(id, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserDepositInfo provides a mock function with given fields: id
func (_m *AdminService) UserDepositInfo(id int) (*dto.UserDepositInfo, error) {
	ret := _m.Called(id)

	var r0 *dto.UserDepositInfo
	if rf, ok := ret.Get(0).(func(int) *dto.UserDepositInfo); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserDepositInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRate provides a mock function with given fields: id, data
func (_m *AdminService) UserRate(id int, data *dto.ChangeInterestRateReq) error {
	ret := _m.Called(id, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, *dto.ChangeInterestRateReq) error); ok {
		r0 = rf(id, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UsersRate provides a mock function with given fields: data
func (_m *AdminService) UsersRate(data *dto.ChangeInterestRateReq) error {
	ret := _m.Called(data)

	var r0 error
	if rf, ok := ret.Get(0).(func(*dto.ChangeInterestRateReq) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewAdminService interface {
	mock.TestingT
	Cleanup(func())
}

// NewAdminService creates a new instance of AdminService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAdminService(t mockConstructorTestingTNewAdminService) *AdminService {
	mock := &AdminService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
